apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: abl-gitops-repo # v spoločnom klastri je nasadených viacero takýchto objektov
  namespace: wac-hospital
spec:
  interval: 1m0s
  ref:
    branch: main
  timeout: 1m0s
  url: https://github.com/a-blaho/ambulance-gitops
# ak používate privátny repozitár nezabudnite doplniť autentifikačné údaje
# secretRef:
#    name: abl-repository-pat
