apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: # zoznam manifestov - objektov,
  # ktoré sú súčasťou tejto aplikácie
  - "https://github.com/a-blaho/ambulance-webapi//deployments/kustomize/install" # ?ref=v1.0.1
